### ISSUE TITLE
how render json 

### ISSUE THREAD

**Issue by tablecell** [eko/gofast#5]
for restful api  or  client post json

**Comment by eko** [comment]
Hi @tablecell,

Using `context.GetResponse()` you can retrieve the `http.ResponseWriter` object, so you can render JSON this way:

```go
response := c.GetResponse()
response.Header().Set("Content-Type", "application/json")
response.Write([]byte(`{"hello": "world"}`))
```

Closing this issue as there is no issue here, please feel free to contact me for more details.

Thank you
